### ISSUE TITLE
Why component can't be PascalCase?

### ISSUE THREAD

**Issue by keshikashviligio** [NishantSinghChandel/reactjs-component-generator#13]
Hi, 
rg component MyComponent -d ./pages/emails/components
result: myComponent folder with myComponent.js and myComponent.scss files

I need to generate MyComponent folder with MyComponent.js and scss

**Comment by NishantSinghChandel** [comment]
hey keshikashviligo, you can change the file configuration by following these commands -
rg show-templates
choose components folder and change the file name extension to pc (pascal case) next time it will generate as per your request.
