### ISSUE TITLE
New component not in PascalCase

### ISSUE THREAD

**Issue by hsellik** [NishantSinghChandel/reactjs-component-generator#15]
Hi,

Whenever I create a component like this:
```
npx reactjs-component-generator@1.3.7
npx: installed 116 in 8.899s
React Generator [Author: Nishant Singh]
? What do you want to generate ? component
? What name do you want to use? VisualizeAst
? Where do you want to create the component? ./src/components/
```
The generator creates files and class with the first character lower cased:
```
export default class visualizeAst extends Component {
    // constructor(props) {
    //     super(props);
    //     this.state = {};
    // }
    render() {
      return <div className="component-visualize-ast">Hello! component visualizeAst</div>;
    }
  }
```

I know I can import it in PascalCase myself later, but is this intended behaviour? I would expect the generator to not lower case the first character.

**Comment by NishantSinghChandel** [comment]
You can easily modify the code it is already in read me. 
For this you can just use these steps:
1. rg show-templates. Then it will open the file explorer.
2. Select component folder.
3. open {name_cc}.js
4. Inside that you can change the class name as {name_pc} and save the file. Here cc - camelCase pc-PascalCase etc.
